[package]
name = "miracools-first"
license = "MIT"
version = "0.1.0"
edition = "2024"
description = "A fun game where you guess what number the computer has chosen."

[dependencies]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3